// Generated by: main
// TypeWriter: set
// Directive: +gen on Nowa

package nepu

// Set is a modification of https://github.com/deckarep/golang-set
// The MIT License (MIT)
// Copyright (c) 2013 Ralph Caraveo (deckarep@gmail.com)

// The primary type that represents a set
type NowaSet map[Nowa]struct{}

// Creates and returns a reference to an empty set.
func NewNowaSet(a ...Nowa) NowaSet {
	s := make(NowaSet)
	for _, i := range a {
		s.Add(i)
	}
	return s
}

// ToSlice returns the elements of the current set as a slice
func (set NowaSet) ToSlice() []Nowa {
	var s []Nowa
	for v := range set {
		s = append(s, v)
	}
	return s
}

// Adds an item to the current set if it doesn't already exist in the set.
func (set NowaSet) Add(i Nowa) bool {
	_, found := set[i]
	set[i] = struct{}{}
	return !found //False if it existed already
}

// Determines if a given item is already in the set.
func (set NowaSet) Contains(i Nowa) bool {
	_, found := set[i]
	return found
}

// Determines if the given items are all in the set
func (set NowaSet) ContainsAll(i ...Nowa) bool {
	for _, v := range i {
		if !set.Contains(v) {
			return false
		}
	}
	return true
}

// Determines if every item in the other set is in this set.
func (set NowaSet) IsSubset(other NowaSet) bool {
	for elem := range set {
		if !other.Contains(elem) {
			return false
		}
	}
	return true
}

// Determines if every item of this set is in the other set.
func (set NowaSet) IsSuperset(other NowaSet) bool {
	return other.IsSubset(set)
}

// Returns a new set with all items in both sets.
func (set NowaSet) Union(other NowaSet) NowaSet {
	unionedSet := NewNowaSet()

	for elem := range set {
		unionedSet.Add(elem)
	}
	for elem := range other {
		unionedSet.Add(elem)
	}
	return unionedSet
}

// Returns a new set with items that exist only in both sets.
func (set NowaSet) Intersect(other NowaSet) NowaSet {
	intersection := NewNowaSet()
	// loop over smaller set
	if set.Cardinality() < other.Cardinality() {
		for elem := range set {
			if other.Contains(elem) {
				intersection.Add(elem)
			}
		}
	} else {
		for elem := range other {
			if set.Contains(elem) {
				intersection.Add(elem)
			}
		}
	}
	return intersection
}

// Returns a new set with items in the current set but not in the other set
func (set NowaSet) Difference(other NowaSet) NowaSet {
	differencedSet := NewNowaSet()
	for elem := range set {
		if !other.Contains(elem) {
			differencedSet.Add(elem)
		}
	}
	return differencedSet
}

// Returns a new set with items in the current set or the other set but not in both.
func (set NowaSet) SymmetricDifference(other NowaSet) NowaSet {
	aDiff := set.Difference(other)
	bDiff := other.Difference(set)
	return aDiff.Union(bDiff)
}

// Clears the entire set to be the empty set.
func (set *NowaSet) Clear() {
	*set = make(NowaSet)
}

// Allows the removal of a single item in the set.
func (set NowaSet) Remove(i Nowa) {
	delete(set, i)
}

// Cardinality returns how many items are currently in the set.
func (set NowaSet) Cardinality() int {
	return len(set)
}

// Iter() returns a channel of type Nowa that you can range over.
func (set NowaSet) Iter() <-chan Nowa {
	ch := make(chan Nowa)
	go func() {
		for elem := range set {
			ch <- elem
		}
		close(ch)
	}()

	return ch
}

// Equal determines if two sets are equal to each other.
// If they both are the same size and have the same items they are considered equal.
// Order of items is not relevent for sets to be equal.
func (set NowaSet) Equal(other NowaSet) bool {
	if set.Cardinality() != other.Cardinality() {
		return false
	}
	for elem := range set {
		if !other.Contains(elem) {
			return false
		}
	}
	return true
}

// Returns a clone of the set.
// Does NOT clone the underlying elements.
func (set NowaSet) Clone() NowaSet {
	clonedSet := NewNowaSet()
	for elem := range set {
		clonedSet.Add(elem)
	}
	return clonedSet
}
